<?php

namespace Sumer5020\ZohoBooks\DTOs;

/**
 * Class TaskDTO
 * Data Transfer Object for a Task.
 */
class TaskDto
{
    /** @var string Unique ID of the project generated by the server */
    public string $project_id;

    /** @var string Unique ID of the task generated by the server */
    public string $task_id;

    /** @var string The current ID of the currency */
    public string $currency_id;

    /** @var string Customer ID of the customer for whom the task is created */
    public string $customer_id;

    /** @var string The name of the task. Max-length [100] */
    public string $task_name;

    /** @var string The name of the project */
    public string $project_name;

    /** @var string Name of the customer to whom the task is created */
    public string $customer_name;

    /** @var float The total hours that are billed */
    public float $billed_hours;

    /** @var float Total hours logged in the project */
    public float $log_time;

    /** @var float Total hours that are unbilled */
    public float $un_billed_hours;

    public function __construct(array $data)
    {
        $this->project_id = $data['project_id'] ?? '';
        $this->task_id = $data['task_id'] ?? '';
        $this->currency_id = $data['currency_id'] ?? '';
        $this->customer_id = $data['customer_id'] ?? '';
        $this->task_name = $data['task_name'] ?? '';
        $this->project_name = $data['project_name'] ?? '';
        $this->customer_name = $data['customer_name'] ?? '';
        $this->billed_hours = $data['billed_hours'] ?? 0.0;
        $this->log_time = $data['log_time'] ?? 0.0;
        $this->un_billed_hours = $data['un_billed_hours'] ?? 0.0;
    }
}
